client_config_backend: file
client_config:
    client_id: 70120460348-l81635077v0flbklqeaj5k7daq67cila.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive